// ui/src/views/Settings.vue
<script setup lang="ts">
import { SettingsPanel } from '@/components'
</script>

<template>
  <div class="flex h-full min-h-0 flex-col overflow-hidden">
    <div class="min-h-0 flex-1 overflow-y-auto overflow-x-hidden p-4">
      <div class="mx-auto w-full max-w-3xl">
        <SettingsPanel />
      </div>
    </div>
  </div>
</template>

// crates/lynx-proxy/src/routes/settings.tsx
import { createFileRoute, Outlet } from '@tanstack/react-router';
import { SettingsMenu } from './settings/components/SettingsMenu';

export const Route = createFileRoute('/settings')({
  component: RouteComponent,
});

function RouteComponent() {
  return (
    <div className="animate-fade-in flex flex-1 justify-center">
      <div className="flex flex-1 min-w-[500px] max-w-[800px] flex-col gap-4 scroll-auto px-4">
        <SettingsMenu />
        <div className="my-2 flex flex-col flex-1 overflow-auto">
          <Outlet />
        </div>
      </div>
    </div>
  );
}
